export const students = [
  {
    name: "Anthony",
    year: 2022,
    content: "Asso jeux de société",
    chosen: false,
    id: 0,
  },
  {
    name: "Brandon",
    year: 2019,
    content: "Site édition de bande dessinée",
    chosen: false,
    id: 1,
  },
  {
    name: "Raouf",
    year: 2014,
    content: "Présentation web 3",
    chosen: false,
    id: 2,
  },
  {
    name: "Jérémy",
    year: 1994,
    content: "Tatouage avec achat",
    chosen: false,
    id: 3,
  },
  {
    name: "Loïc",
    year: 1999,
    content: "Blog forum jeux vidéos",
    chosen: false,
    id: 4,
  },
  {
    name: "Francis",
    year: 2003,
    content: "Cours de danse particulier",
    chosen: false,
    id: 5,
  },
  {
    name: "Gwendal",
    year: 2023,
    content: "Jeux de rôles",
    chosen: false,
    id: 6,
  },
  {
    name: "Marion",
    year: 2011,
    content: "Boutique de recettes et de services",
    chosen: false,
    id: 7,
  },
  {
    name: "Kenza",
    year: 2011,
    content: "Site lait maternel",
    chosen: false,
    id: 8,
  },
  {
    name: "Pauline",
    year: 2011,
    content: "Site éducation canine",
    chosen: false,
    id: 9,
  },
];
